### ISSUE TITLE
Admin Dashboard 

### ISSUE THREAD

**Issue by krismp** [nodefluxio/weber#48]
**Is your feature request related to a problem? Please describe.**
Currently, we use a database seeder to store initial data for our demo app, and we don't have any flexibility if we want to add or update the data.

**Describe the solution you'd like**
Develop a simple dashboard admin using a stack like Django, Ruby on Rails, Laravel, or whatever tech stack you may prefer, but please take concern that you need to weigh the expertise of your team and use it as a basis to judge your choice of the tech stack.

Use the same database as the backend

**Comment by sonadztux** [comment]
in development here https://github.com/nodefluxio/weber-insight thanks @lazuardyk
