### ISSUE TITLE
[Backend] routes group parent to `/api/v1`

### ISSUE THREAD

**Issue by asyafalni** [nodefluxio/weber#64]
**Is your feature request related to a problem? Please describe.**
To avoid mixing parent browser URL and backend URL, backend API should be running on separate endpoint

**Describe the solution you'd like**
nested current group on new group `/api/v1/

**Comment by sonadztux** [comment]
Gue take ini ya. Btw yang di frontend ada yang perlu disesuaikan ga, Mas @asyafalni?

**Comment by asyafalni** [comment]
> Gue take ini ya. Btw yang di frontend ada yang perlu disesuaikan ga, Mas @asyafalni?

Di sisi frontend cuma setting env aja kok, secara code ga ada yang perlu diubah
