### ISSUE TITLE
[Frontend] Add favicon

### ISSUE THREAD

**Issue by krismp** [nodefluxio/weber#94]
# Description

Please use Nodeflux's favicon, currently NextJS use Vercel icon by default

## Actual

<img width="127" alt="Screen Shot 2021-11-09 at 14 50 26" src="https://user-images.githubusercontent.com/6040035/140883557-40f6c3f8-b108-4e96-9004-64f54089ce7d.png">

## Expected
<img width="114" alt="Screen Shot 2021-11-09 at 14 51 53" src="https://user-images.githubusercontent.com/6040035/140883774-2b602517-5fdf-4c0c-bfc4-f2c05e156452.png">

as in https://cloud.nodeflux.io/

**Comment by rizkybaihaqy** [comment]
btw ini assetnya minta tim product atau ambil aja dari nodeflux cloud?

**Comment by krismp** [comment]
@rizkybaihaqy ambil aja yg paling cepet dulu, dari nodeflux cloud brarti?
